sudo: required
dist: trusty
git:
  submodules: false
language: c
compiler: gcc

before_install:
- echo "deb https://dl.bintray.com/rwth-os/hermitcore vivid main" | sudo tee -a /etc/apt/sources.list
- sudo apt-get -qq update
- sudo apt-get install -y nasm texinfo libmpfr-dev libmpc-dev libgmp-dev libisl-dev packaging-dev
- sudo apt-get install -y --force-yes gcc-hermit-bootstrap

script:
- cd ..
- mv newlib newlib-2.4.0
- tar -czf newlib_2.4.0.orig.tar.gz newlib-2.4.0 --exclude=.git
- cd newlib-2.4.0
- debuild -e PATH -us -uc -j2

deploy:
  on: production
  provider: bintray
  file: .bintray_descriptor.json
  user:
    secure: tyfJpir8tFlcbo3m7MC6wVSQpNa6hwNISIdVlgY8CbL+tq3LMm/FxXFENB7NfTLb1pHQiCxV+q6pWTMI1O0KZSkGk7utA7inAVGubQSZFGBzuV9XGcT9HMHjW6Z+jk87n7+apkSiV8EvFjf3ZVZS9BsX0hZuBNYdGsv6O9vGvoFi6U3GjTC0FcN47CD7HVfcO0oQCrFGvqSthwJDp5ApZZKGwmdmlPnhgqdRrRKSUiY5QxKOHbvdiQn4SA3O3g0Wti19I0qYwfr4RPqCyrcOfD5In/IZW772pp+DjDpK6e8VDaCVzWhtkPqWqj3wGY7nxO9K2Xp6q3qS5ZyhHHFJhQMnyxRPGRWtoKV8IAo8CIJtICdgA/daVrrSqVfjHcU20k9gAhQzm3jwlJ3oldgwah7Sh8PrwxSb7rT9cmBeEVZgTjYVQY1srUK+PzM8bNmQEByjxCu5y4vsT/hXkgyH/3ZuKO6oXS+dDMU6pGE5nKN5O3xa8IGvGYqzkqehCgN5qVigAWQ9sglo4R15V3Xk6/Int8/4GbuOUBGAUaLtxWUsXxv3XWgj7FB1NmpPvOT4Nkto5LJ4jrns5CTRvZjy2mXug1phzglO7waUNmxXisEcJpbU8JRWQUR1/Vs1S9tcB/i4WhYPjdAeznJZMQ/m8Dc6vb/KLeeeUc9h3KdoppE=
  key:
    secure: a03NKi1Mq1kbI8+oUt5oww4G4+a2981fVTq3etT1ESCQQMtuNDF9qeXkXaRxPNcLNb60DJ2fB+Nv3QlB2MppAtv1i3ImwMnRBZGYA97hutCD4C0BWyVMglxKEcmgVH592n8KoiQpgnb+pOjIP7LxsBZ2APs/Gk9TWYXqtNAsNw9e61TurUJsGyEzq6CkDnrMwJ29WQTJZne6SEdQ1muKcgDWYTXY/+BsGoZOcmJC+n66PepGSRUUf2xog+PlhhIMm44aDr2LaHtaPp2JYrTUObMdbXzYVRA90ptRIrza2k/V2Uh7SxfXqW6zNs9DoFTp9gwz3ZAgfizbWBFimvBhEfPiWagycOP59PFAxP3/DwfMK9rpeg0GDsFjGi72IYaIr7n6430zslmnQsb4PiDi7vL7KamYQYJi0okUG5tXWiCqO1YRmjA7FRMXN8B3SLLrRRAqLM/QZ5b/SuMG9ccIyor2rhxbYX+4/g4aAyqCdh8c4X9lQXVvna8D/ify81QSMLXWM1JkL3IKnK/Cqr1bBK/mQSQBUc2JhlZAyiQhI9GO7s1wxDyZO9okYYCM8dfvQ7bcyeJR/pf/rrJTydUVEK5ETObP+QMXz2mA/F8+VXY6IAbHGyB4vRdZJ8BcxGLouqSndhYVa6dJ1oAiOI2XVh3DWG1iDt5jJtNGVswgExA=

env:
   global:
     - PATH=$PATH:/opt/hermit/bin
