Document: newlib
Title: Debian newlib Manual
Author: <insert document author here>
Abstract: This manual describes what newlib is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/newlib/newlib.sgml.gz

Format: postscript
Files: /usr/share/doc/newlib/newlib.ps.gz

Format: text
Files: /usr/share/doc/newlib/newlib.text.gz

Format: HTML
Index: /usr/share/doc/newlib/html/index.html
Files: /usr/share/doc/newlib/html/*.html
